export enum OrderStatus {
  READY = 'READY',
  CANCELED = 'CANCELED',
  COMPLATED_PAYMENT = 'COMPLATED_PAYMENT',
  FAILED_PAYMENT = 'FAILED_PAYMENT',
  DELIVERY_STARTED = 'DELIVERY_STARTED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  COMPLETED = 'COMPLETED',
}
